// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreaateTodoInput struct {
	Text string `json:"text"`
}

type UpdateToDoInput struct {
	ID   string  `json:"id"`
	Text *string `json:"text"`
	Done *bool   `json:"done"`
}
